name: app_movies
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  carousel_slider: ^4.0.0
  youtube_player_flutter: ^9.0.1
  http: ^1.1.2
  flutter_login: ^3.2.0
  provider: ^6.1.2
  shared_preferences: ^2.0.6
  auto_size_text: ^3.0.0
  meta: any
  mockito: ^5.4.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/jiji.png
    - assets/images/livro1_2.png
    - assets/images/livro1.png
    - assets/images/livro1_1.png
    - assets/images/livro1_3.png
    - assets/images/livro2.png
    - assets/images/livro2_1.png
    - assets/images/livro2_2.png
    - assets/images/livro2_3.png
    - assets/images/livro3.png
    - assets/images/livro3_1.png
    - assets/images/livro3_2.png
    - assets/images/livro3_3.png
    - assets/images/livro4.png
    - assets/images/livro4_1.png
    - assets/images/livro4_2.png
    - assets/images/livro4_3.png
    - assets/images/login.png
    - assets/images/jiji2.png
    - assets/images/corequebrado.png
    - assets/images/nuvem.png

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/MerriweatherBlack.ttf
          weight: 900
    - family: Mulish
      fonts:
        - asset: assets/fonts/MuliBold.ttf
          weight: 700
        - asset: assets/fonts/MuliRegular.ttf
